name: Code Quality checks
on:
    pull_request:
        branches: [main]
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    prettier:
        name: Prettier
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node-version: [18]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install dependencies
              run: npm install -D prettier

            - name: Check formatting with Prettier
              run: npm run prettier:check
